os: windows
#language: shell
language: cpp

env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build"

script:
  - cmd.exe //C 'config-and-make.cmd'
#  echo export1 && export PATH=$MSBUILD_PATH:$PATH && MSBuild.exe -help
#  - cmd.exe //C vcvarsall.bat x86 nmake
  - echo prepare for build && choco install aria2 && cd $TRAVIS_BUILD_DIR && chmod +x *.sh -v && ./make-build-cache.sh
  - echo setup Active Perl && chmod +x *.msi && ActivePerl-5.28.1.0000-MSWin32-x64-865dc3eb.msi /qn /norestart || echo error setup perl
  - echo setup OpenSSL && dir && chmod +x Win*.exe && ./setup-openssl.cmd && echo done setup openssl || echo error setup openssl
  - dir "C:\Program Files (x86)"
  - echo show version perl && perl --version
  - echo configure && cd qt5 && ls -la && chmod +x *.bat && export PATH=$MSBUILD_PATH:$PATH && ../config-and-make.cmd
#  - echo stage build && cd $TRAVIS_BUILD_DIR && ls -la && ./build.sh
#  - echo pack windows && cd $TRAVIS_BUILD_DIR/deltachat-desktop && cd dist && mv win-unpacked ../release/ && cd .. && 7z a -tzip -r deltachat-win.zip release && mv deltachat-win.zip $TRAVIS_BUILD_DIR/
#  - echo store and deploy to github && cd $TRAVIS_BUILD_DIR/ && ./store-cache.sh

deploy:
  provider: releases
  api_key:
    secure: MHOFxtukgy4DdA0aglqX/ngEpbzwsPLvtNPpv9yfhugp0Y7Kd9xNzm4Yg7iVEoCUpvb6+sSZNKdlzWTZPVomFC0h1ZR+ufLBcI3ZjumSx/jM4d46e0mr5K/n/+IwhgBAMjharl6aT7fMJu371Il9M7uIOiYXj1C+DKurmdemULiMFTtbPMSC/p46SX3wJVglIes2oLPts0gl57hgaxXhHBd+pqVzOtKxelkAH8r88wejvFvaPMJNL5dvIyCaDuWndrbe8ZRQLlj0B6xOrOeAfAJdCZ0CDB8XAaCMVVC+X4aR639vTHW9K5Nn2jV/xVDXQr6H2vHpeHMgtgucfgE4xm4FmJuWht38Q6D9Px6yG96KLEKHh4qGRTKk8xBHs97cbSj9bHXIqnV4IZuWSM/IAEMkGpWIr3PUAFDNSpS8y1l9Yqa8Xt6PGY/9MuN2WNRhZUXVP/VNtN5beGItLtxXzhCeDInvGGrzF6ewwLFZ5nfwWMAY7hmYYpyV8TdwR6Wjp5eu8fRHnDviHRYsxG87wM8vEcPo0h34SzXxIywKETgRo28vyJgHggcOta2mmowRw6QasmslQujf91+lWWVTnt0LoVVTed4XAWEFeIcBdyaqxhDLkPdJaO65U2gtZR5DcAW7VImbE4+bU2D60N7NpKVAzuJ8fGkVaIDGsvHR6fQ=
  file: 
    - qt-sources.7z.001
#    - qt-sources.7z.002
#    - qt-sources.7z.003
  prerelease: true
  skip_cleanup: true
  draft: true
  on:
    repo: homdx/test-win-build
