os: windows
language: shell

script:
  - ls /c/Users
    #- wget https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe && ./rustup-init.exe -s --default-toolchain nightly
  - choco install nodejs.install 7zip.install && ls -la && cd $TRAVIS_BUILD_DIR && ls -la && 7z a -tzip -r test1.zip .travis.yml && ls -la
  - export PATH=/c/Users/travis/.cargo/bin:$PATH && cd /c/ProgramData/chocolatey/bin && wget https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe && ./rustup-init.exe -y --default-toolchain nightly
  - export PATH=/c/Users/travis/.cargo/bin:$PATH && rustc --version
  - export PATH=/c/Users/travis/.cargo/bin:/c/Program\ Files/nodejs:$PATH && cd $TRAVIS_BUILD_DIR && ls -la && git clone https://github.com/deltachat/deltachat-node --recursive && cd deltachat-node && npm install && npm link
  - ls -la && cd $TRAVIS_BUILD_DIR && git clone --recursive https://github.com/deltachat/deltachat-desktop && cd deltachat-desktop && export PATH=/c/Users/travis/.cargo/bin:/c/Program\ Files/nodejs:$PATH && npm link deltachat-node && npm install && echo build deltachat dekstop windows && npm run build && echo test deltachat windows && npm run test
  - ls -la && cd $TRAVIS_BUILD_DIR/deltachat-desktop && ls -la && cd dist && ls -la && mv win-unpacked ../release/ && ls -la && cd .. && ls -la && 7z a -tzip -r deltachat-win.zip release && mv deltachat-win.zip release/ && ls -la release
#    - choco install cygwin --params "/NoStartMenu"
#    - choco install cyg-get
#    - /c/ProgramData/chocolatey/bin/cyg-get.bat dos2unix patch unzip automake make bzip2 libsqlite-3-devel libtool gcc-g++ openssl-devel wget gcc-core cygwin-devel
##&& /c/ProgramData/chocolatey/bin/cyg-get.bat dos2unix patch unzip automake make bzip2 libsqlite-3-devel libtool gcc-g++ openssl-devel wget gcc-core cygwin-devel cmake-3.13.1
## imake makedepend libarchive13 libcom_err2 libcurl4 libexpat1 libext2fs2 libgssapi_krb5_2 libjsoncpp19 libk5crypto3 libkrb5_3 libkrb5support0 liblz4_1 libnghttp2_14 libopenldap2_4_2 librhash0 libsasl2-devel libsasl2_3 libslang2 libsqlite3-devel libsqlite3_0 libssh2_1 libuv1 perl-TimeDate cmake
##    - ls -la && echo 2 && ls -la / && echo 3 && ls -la /c && echo 4 && ls -la /c/ProgramData && echo 5 && ls -la /c/ProgramData/chocolatey && echo 6 && ls -la /c/ProgramData/chocolatey/bin/ && echo 7 && ls -la /c/tools/cygwin/ && echo 8 && ls -la /c/tools/cygwin/bin
#    - ./setup-cygwin-packages.cmd
#    - ./travis-step1-bzip.cmd
#    - mkdir -pv /c/Code/libetpan && cd /c/Code/libetpan && git clone --recursive https://github.com/dinhviethoa/libetpan.git && cd $TRAVIS_BUILD_DIR
#    - ./travis-step2-libetpan.cmd
#    - /c/ProgramData/chocolatey/bin/cyg-get.bat dos2unix patch unzip automake make bzip2 libsqlite-3-devel libtool gcc-g++ openssl-devel wget gcc doxygen libllvm5 libclang5 libedit0 libxapian30 cmake xz libjson-c-devel libuv1 librhash0 libjsoncpp19 zlib-devel python3 git
#    - ./travis-step3-cmocka.cmd
#    - wget https://github.com/randombit/botan/archive/2.9.0.tar.gz
#    - ./travis-step4-1-botan.cmd
#    - ./travis-step4-2-botan.cmd
#    - wget https://github.com/riboseinc/rnp/archive/v0.12.0.tar.gz
#    - ./travis-step5-rnp.cmd
#    - choco install nodejs.install && ls -la '/c/Program Files/nodejs/' && /c/Program\ Files/nodejs/npm --version
#    - echo python3 and pip setup && /c/ProgramData/chocolatey/bin/cyg-get.bat python3 python3-pip python3-devel gcc-g++ gcc-fortran libgcrypt20 libgpg-error0 libxslt python3-asn1crypto python3-cffi python3-chardet python3-cryptography python3-idna	python3-lockfile python3-lxml python3-openssl python3-ply python3-pycparser	python3-requests python3-urllib3  python3-wheel
#    - ./travis-step6-ninja-meson.cmd
#    - ls -la && wget --quiet https://github.com/deltachat/deltachat-node/archive/v0.39.0.tar.gz && tar -xf v0.39.0.tar.gz && mv deltachat-node-0.39.0 deltachat-node && cd deltachat-node && wget --quiet https://github.com/deltachat/deltachat-core/archive/v0.39.1.tar.gz && tar -xf v0.39.1.tar.gz && rm -rf deltachat-core && mv deltachat-core-0.39.1 deltachat-core && cd .. 
#    - export PATH=/c/Program\ Files/nodejs/:$PATH && npm --version && cd deltachat-node && npm install || echo need build after installed requirements && cd ..
#    - ./travis-step7-build-delta.cmd

deploy:
  provider: releases
  api_key:
    secure: MHOFxtukgy4DdA0aglqX/ngEpbzwsPLvtNPpv9yfhugp0Y7Kd9xNzm4Yg7iVEoCUpvb6+sSZNKdlzWTZPVomFC0h1ZR+ufLBcI3ZjumSx/jM4d46e0mr5K/n/+IwhgBAMjharl6aT7fMJu371Il9M7uIOiYXj1C+DKurmdemULiMFTtbPMSC/p46SX3wJVglIes2oLPts0gl57hgaxXhHBd+pqVzOtKxelkAH8r88wejvFvaPMJNL5dvIyCaDuWndrbe8ZRQLlj0B6xOrOeAfAJdCZ0CDB8XAaCMVVC+X4aR639vTHW9K5Nn2jV/xVDXQr6H2vHpeHMgtgucfgE4xm4FmJuWht38Q6D9Px6yG96KLEKHh4qGRTKk8xBHs97cbSj9bHXIqnV4IZuWSM/IAEMkGpWIr3PUAFDNSpS8y1l9Yqa8Xt6PGY/9MuN2WNRhZUXVP/VNtN5beGItLtxXzhCeDInvGGrzF6ewwLFZ5nfwWMAY7hmYYpyV8TdwR6Wjp5eu8fRHnDviHRYsxG87wM8vEcPo0h34SzXxIywKETgRo28vyJgHggcOta2mmowRw6QasmslQujf91+lWWVTnt0LoVVTed4XAWEFeIcBdyaqxhDLkPdJaO65U2gtZR5DcAW7VImbE4+bU2D60N7NpKVAzuJ8fGkVaIDGsvHR6fQ=
  file: release/deltachat-win.zip
  prerelease: true
  on:
    repo: homdx/test-win-build
