os: windows
language: shell

script:
  - choco install nodejs.install aria2
  #- export PATH=/c/Users/travis/.cargo/bin:$PATH && cd /c/ProgramData/chocolatey/bin && wget --quiet https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe && ./rustup-init.exe -y --default-toolchain nightly
  # - echo 01 && mkdir -pv /c/Users/travis/.cargo && echo 02 && cd '/c/Users/travis/.cargo' && echo 03 && wget --quiet https://github.com/homdx/test-win-build/releases/download/cached-0.104a.0/cargo.7z && echo 04 && 7z x -y cargo.7z && echo 05 && ls -la && rm -fv cargo.7z && ls -la && cd .. && echo 06 && export PATH=/c/Users/travis/.cargo/bin:$PATH && mkdir -pv /c/Users/travis/.rustup && echo 07 && cd /c/Users/travis/.rustup && echo 08 && wget --quiet https://github.com/homdx/test-win-build/releases/download/cached-0.104a.0/rustup-arc.7z && echo 09 && 7z x -y rustup-arc.7z && rm -fv rustup-arc.7z && cd .. && rustc --version
  - chmod +x make-build-cache.sh && ./make-build-cache.sh
#  - export PATH=/c/Users/travis/.cargo/bin:$PATH && rustc --version && echo find files &&  find /c -name  "*config*" -print
  - export PATH=/c/Users/travis/.cargo/bin:/c/Program\ Files/nodejs:$PATH && cd $TRAVIS_BUILD_DIR && echo cp cargo-config2 -vf /c/Users/travis/.cargo/config && echo cargo update --verbose && cargo --version && git clone https://github.com/deltachat/deltachat-node --recursive && cd deltachat-node && mkdir -pv deltachat-core-rust && cd deltachat-core-rust && wget --quiet https://github.com/homdx/test-win-build/releases/download/cached-0.104a.0/deltachat-core-rust.7z && 7z x -y deltachat-core-rust.7z && rm -fv deltachat-core-rust.7z && cat $TRAVIS_BUILD_DIR/cargo-config2 >>Cargo.toml && cat Cargo.toml && cargo --version && echo manual update && cargo update --verbose && cd .. && cargo --version && echo compile npm && npm install && npm link
  - cd $TRAVIS_BUILD_DIR && git clone --recursive https://github.com/deltachat/deltachat-desktop && cd deltachat-desktop && export PATH=/c/Users/travis/.cargo/bin:/c/Program\ Files/nodejs:$PATH && npm link deltachat-node && npm install && echo build deltachat dekstop windows && npm run build && echo test deltachat windows && npm run test
  - cd $TRAVIS_BUILD_DIR/deltachat-desktop && npm run dist || true
  - cd $TRAVIS_BUILD_DIR/deltachat-desktop && cd dist && mv win-unpacked ../release/ && cd .. && 7z a -tzip -r deltachat-win.zip release && mv deltachat-win.zip $TRAVIS_BUILD_DIR/
  - cd $TRAVIS_BUILD_DIR/ && chmod +x store-cache.sh && ./store-cache.sh
#  - cd /c/Users/travis/.cargo && 7z a -bsp1 -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -r $TRAVIS_BUILD_DIR/cargo.7z * || true
#  - cd $TRAVIS_BUILD_DIR/deltachat-node/deltachat-core-rust/  && 7z a -bsp1 -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -r $TRAVIS_BUILD_DIR/deltachat-core-rust.7z * || true
#  - cd /c/Users/travis/.rustup/ && 7z a -bsp1 -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -r $TRAVIS_BUILD_DIR/rustup-arc.7z * || true
  - cd $TRAVIS_BUILD_DIR && ls -la # &&  find /c -name  "rustc.exe" -print && find /c -name  "*config*" -print

deploy:
  provider: releases
  api_key:
    secure: MHOFxtukgy4DdA0aglqX/ngEpbzwsPLvtNPpv9yfhugp0Y7Kd9xNzm4Yg7iVEoCUpvb6+sSZNKdlzWTZPVomFC0h1ZR+ufLBcI3ZjumSx/jM4d46e0mr5K/n/+IwhgBAMjharl6aT7fMJu371Il9M7uIOiYXj1C+DKurmdemULiMFTtbPMSC/p46SX3wJVglIes2oLPts0gl57hgaxXhHBd+pqVzOtKxelkAH8r88wejvFvaPMJNL5dvIyCaDuWndrbe8ZRQLlj0B6xOrOeAfAJdCZ0CDB8XAaCMVVC+X4aR639vTHW9K5Nn2jV/xVDXQr6H2vHpeHMgtgucfgE4xm4FmJuWht38Q6D9Px6yG96KLEKHh4qGRTKk8xBHs97cbSj9bHXIqnV4IZuWSM/IAEMkGpWIr3PUAFDNSpS8y1l9Yqa8Xt6PGY/9MuN2WNRhZUXVP/VNtN5beGItLtxXzhCeDInvGGrzF6ewwLFZ5nfwWMAY7hmYYpyV8TdwR6Wjp5eu8fRHnDviHRYsxG87wM8vEcPo0h34SzXxIywKETgRo28vyJgHggcOta2mmowRw6QasmslQujf91+lWWVTnt0LoVVTed4XAWEFeIcBdyaqxhDLkPdJaO65U2gtZR5DcAW7VImbE4+bU2D60N7NpKVAzuJ8fGkVaIDGsvHR6fQ=
  file: 
    - deltachat-win.zip
    - cargo.7z
    - rustup-arc.7z
    - deltachat-core-rust.7z
    - deltachat-snapshot-sources.7z
    - cargo-indexes.7z
  prerelease: true
  skip_cleanup: true
  draft: true
  on:
    repo: homdx/test-win-build
